# Generated by Django 5.2.7 on 2025-10-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('pro_discr1', models.CharField(max_length=200)),
                ('pro_discr2', models.CharField(blank=True, max_length=200, null=True)),
                ('pro_discr3', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(max_length=50)),
                ('weekly_product', models.BooleanField(default=False)),
                ('new_arrivals', models.BooleanField(default=False)),
                ('old_price', models.CharField(max_length=10)),
                ('current_price', models.CharField(max_length=10)),
                ('product_image', models.ImageField(upload_to='Products/')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productcode')),
            ],
        ),
    ]
